name: settings_test
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  image_picker: ^1.0.4
  flutter:
    sdk: flutter
  provider: ^6.1.1
  io: ^1.0.4
  animated_text_kit:
  firebase_auth: ^4.14.0
  firebase_core: ^2.22.0
  cloud_firestore: ^4.13.1
  firebase_storage: ^11.5.1
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
